# Generated by Django 5.1.1 on 2024-09-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterpiece", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artwork",
            name="hook",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artwork",
            name="image",
            field=models.ImageField(default="No hook", upload_to="artworks/"),
            preserve_default=False,
        ),
    ]
