# Generated by Django 5.1.1 on 2024-10-13 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masterpiece", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("style", models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name="artwork",
            name="rag_url",
        ),
        migrations.AddField(
            model_name="artwork",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="artwork",
            name="rag_path",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="artwork",
            name="artist_fk",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artwork",
                to="masterpiece.artist",
            ),
        ),
    ]
