# Generated by Django 5.1.1 on 2024-09-17 17:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("masterpiece", "0002_artwork_hook_artwork_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="artwork",
            name="image",
        ),
    ]
